---
local_volume_provisioner_bootstrap_image_repo: registry.cn-hangzhou.aliyuncs.com/hxpdocker/local-volume-provisioner-bootstrap
local_volume_provisioner_bootstrap_image_tag: v1.0.0

local_volume_provisioner_image_repo: registry.cn-hangzhou.aliyuncs.com/hxpdocker/local-volume-provisioner
local_volume_provisioner_image_tag: v1.0.0
