---
# Limits
weave_memory_limit: 400M
weave_cpu_limit: 30m
weave_memory_requests: 64M
weave_cpu_requests: 10m

# This two variable are automatically changed by the weave's role, do not manually change these values
# To reset values :
# weave_seed: unset
# weave_peers: unset
weave_seed: uninitialized
weave_peers: uninitialized

# this variable is use in seed mode
weave_ip_current_cluster: "{% for host in groups['k8s-cluster'] %}{{ hostvars[host]['ip'] | default(hostvars[host]['ansible_default_ipv4']['address']) }}{% if not loop.last %} {% endif %}{% endfor %}"